name       : cli-visualizer
version    : '1.7'
release    : 2
source     :
    - https://github.com/dpayne/cli-visualizer/archive/1.7.tar.gz : 0445fbfad9707668a70ff146f3f24308f28fa0ae67a7010bfdea0dacba75b75b
license    : MIT
component  : multimedia.audio
summary    : CLI based audio visualizer
description: |
    Command line visualizer. Supports mpd, with experimental support for alsa and pulseaudio. Inspired by C.A.V.A, ncmpcpp, and rainbow!
builddeps  :
    - pkgconfig(fftw3f)
    - pkgconfig(ncursesw)
    - pkgconfig(libpulse)
    - fftw
    - ncurses
setup      : |
    cat Makefile | grep "std=c++14"
    sed -i 's/LIBS += -ltinfo//g' Makefile
    sed -i 's/CXX_FLAGS = -std=c++14/CXX_FLAGS ?= -std=c++14 -D VIS_LOG_DEBUG/g' Makefile
    cat Makefile | grep "std=c++14"
build      : |
    CXXFLAGS="$CXXFLAGS -D VIS_LOG_DEBUG"
    %make
install    : |
    mkdir -p $installdir/usr/bin/
    %make_install PREFIX="$installdir/usr/bin/"
