name       : cli-visualizer
version    : '1.8'
release    : 3
source     :
    - https://github.com/dpayne/cli-visualizer/archive/v1.8.tar.gz : 927e4c18403c7a40397e8698ffefd1b37250be20fa0ec55fda9a82cf9cc8ba51
license    : MIT
component  : multimedia.audio
summary    : CLI based audio visualizer
description: |
    Command line visualizer. Supports mpd, with experimental support for alsa and pulseaudio. Inspired by C.A.V.A, ncmpcpp, and rainbow!
builddeps  :
    - pkgconfig(fftw3f)
    - pkgconfig(ncursesw)
    - pkgconfig(libpulse)
    - fftw
    - ncurses
setup      : |
    cat Makefile | grep "std=c++14"
    sed -i 's/LIBS += -ltinfo//g' Makefile
    sed -i 's/CXX_FLAGS = -std=c++14/CXX_FLAGS ?= -std=c++14 -D VIS_LOG_DEBUG/g' Makefile
    cat Makefile | grep "std=c++14"
build      : |
    CXXFLAGS="$CXXFLAGS -D VIS_LOG_DEBUG"
    %make
install    : |
    mkdir -p $installdir/usr/bin/
    %make_install PREFIX=/usr
