name       : cli-visualizer
version    : '1.8'
release    : 4
source     :
    - https://github.com/dpayne/cli-visualizer/archive/v1.8.tar.gz : 927e4c18403c7a40397e8698ffefd1b37250be20fa0ec55fda9a82cf9cc8ba51
license    : MIT
component  : multimedia.audio
summary    : CLI based audio visualizer
description: |
    Command line visualizer. Supports mpd, with experimental support for alsa and pulseaudio. Inspired by C.A.V.A, ncmpcpp, and rainbow!
builddeps  :
    - pkgconfig(fftw3f)
    - pkgconfig(ncursesw)
    - pkgconfig(libpulse)
    - fftw
    - ncurses
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
